### ISSUE TITLE
mix deps.get can't find the package anymore

### ISSUE THREAD

**Issue by 1player** [jayjun/slugify#7]
Thanks for this package. We're using it in production, and within the past few days mix has been unable to download the package. Looks like a hex issue, but perhaps it's due to some changes on the package.

Using slugify 1.1, `mix deps.get` now breaks with: 

```
Failed to fetch record for 'hexpm/slugify' from registry (using cache instead)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
```

Here's the related hex issue: https://github.com/hexpm/hex/issues/713

**Comment by 1player** [comment]
I've made it work by using the git version, pointing to what I assume is the 1.1 release commit.

Replace `{:slugify, "~> 1.1"}`

With: `{:slugify, github: "jayjun/slugify", ref: "5166495e33b9b6f30be5d93381e103743ed37c4f"}`

**Comment by jayjun** [comment]
1.1.0 is definitely still published.

```bash
$ mix deps.unlock slugify
$ mix deps.get
```
should fix any issues.

Just so happens 1.2.0 went out today so if you’re not ready for a minor release bump, restrict to `~> 1.1.0` before fetching. No breaking changes but separators may be generated slightly differently.

@1player I’ve properly tagged the relevant commits for all releases. Sorry about that.

**Comment by 1player** [comment]
I tries unlocking the deps to no effect, even removing the package manually from mix.lock. 

I'm not at my PC now so I can't really test if anything changed in the past few hours

On Tue, 27 Aug 2019, at 19:05, Tan Jay Jun wrote:
> 1.1.0 is definitely still published.

> $ mix deps.unlock slugify
$ mix deps.get

**Comment by 1player** [comment]
Closing, it's an upstream problem and it's been fixed manually. Tracking issue: https://github.com/hexpm/hexpm/issues/845
